# Generated by Django 5.0.4 on 2024-04-04 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categorys',
            new_name='category_name',
        ),
    ]
